name: VM Nightly
on:
  schedule:
    - cron: 0 0 * * *

env:
  cwd: ${{github.workspace}}/packages/vm

defaults:
  run:
    working-directory: packages/vm

jobs:
  test-vm-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # This is specific to Nightly test 1/2.
      # The job needs to run with a fresh lockfile.
      - run: rm yarn.lock
        working-directory: ${{github.workspace}}

      # This is specific to Nightly test 2/2.
      # Here, we generate new lockfiles
      - run: yarn
        working-directory: ${{github.workspace}}

      - run: yarn run build
        working-directory: ${{github.workspace}}

      - run: yarn run test:API
      - run: yarn run test:API:browser

  test-vm-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # This is specific to Nightly test 1/2.
      # The job needs to run with a fresh lockfile.
      - run: rm yarn.lock
        working-directory: ${{github.workspace}}

      # This is specific to Nightly test 2/2.
      # Here, we generate new lockfiles
      - run: yarn
        working-directory: ${{github.workspace}}

      - run: yarn run build
        working-directory: ${{github.workspace}}

      - run: yarn run test:state:allForks

  test-vm-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # This is specific to Nightly test 1/2.
      # The job needs to run with a fresh lockfile.
      - run: rm yarn.lock
        working-directory: ${{github.workspace}}

      # This is specific to Nightly test 2/2.
      # Here, we generate new lockfiles
      - run: yarn
        working-directory: ${{github.workspace}}

      # This is specific to Nightly test 3/2.
      # In the case lockfiles a.re not so fresh, use information from cache
      - name: Dependency cache.
      # We need this to save cache afterwards, so other jobs can benefit from it.
        uses: actions/cache@v2
        id: cache
        with:
          key: cache-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          path: '**/node_modules'

      - run: yarn run build
        working-directory: ${{github.workspace}}

      - run: yarn run test:blockchain:allForks
        working-directory: '${{ env.cwd }}'

  test-vm-slow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      # This is specific to Nightly test 1/2.
      # The job needs to run with a fresh lockfile.
      - run: rm yarn.lock
        working-directory: ${{github.workspace}}

      # This is specific to Nightly test 2/2.
      # Here, we generate new lockfiles
      - run: yarn
        working-directory: ${{github.workspace}}

      - run: yarn run build
        working-directory: ${{github.workspace}}
      
      - run: yarn run test:state:slow
